// <auto-generated />
using GeekShopping.ProductAPI.Model.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GeekShopping.ProductAPI.Migrations
{
    [DbContext(typeof(MySQLContext))]
    [Migration("20220704002906_SeedProdDataTable")]
    partial class SeedProdDataTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GeekShopping.ProductAPI.Model.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("category_name");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("price");

                    b.Property<string>("image_url")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("image_url");

                    b.HasKey("Id");

                    b.ToTable("product");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            CategoryName = "Categoria produto 3",
                            Description = "Descrição do produto 3",
                            Name = "Produto 3",
                            Price = 30m,
                            image_url = "http://teste.com"
                        },
                        new
                        {
                            Id = 4,
                            CategoryName = "Categoria produto 4",
                            Description = "Descrição do produto 4",
                            Name = "Produto 4",
                            Price = 40m,
                            image_url = "http://teste.com"
                        },
                        new
                        {
                            Id = 5,
                            CategoryName = "Categoria produto 5",
                            Description = "Descrição do produto 5",
                            Name = "Produto 5",
                            Price = 50m,
                            image_url = "http://teste.com"
                        },
                        new
                        {
                            Id = 6,
                            CategoryName = "Categoria produto 6",
                            Description = "Descrição do produto 6",
                            Name = "Produto 6",
                            Price = 60m,
                            image_url = "http://teste.com"
                        },
                        new
                        {
                            Id = 7,
                            CategoryName = "Categoria produto 7",
                            Description = "Descrição do produto 7",
                            Name = "Produto 7",
                            Price = 70m,
                            image_url = "http://teste.com"
                        },
                        new
                        {
                            Id = 8,
                            CategoryName = "Categoria produto 8",
                            Description = "Descrição do produto 8",
                            Name = "Produto 8",
                            Price = 80m,
                            image_url = "http://teste.com"
                        },
                        new
                        {
                            Id = 9,
                            CategoryName = "Categoria produto 9",
                            Description = "Descrição do produto 9",
                            Name = "Produto 9",
                            Price = 90m,
                            image_url = "http://teste.com"
                        },
                        new
                        {
                            Id = 10,
                            CategoryName = "Categoria produto 10",
                            Description = "Descrição do produto 10",
                            Name = "Produto 10",
                            Price = 100m,
                            image_url = "http://teste.com"
                        },
                        new
                        {
                            Id = 11,
                            CategoryName = "Categoria produto 11",
                            Description = "Descrição do produto 11",
                            Name = "Produto 11",
                            Price = 110m,
                            image_url = "http://teste.com"
                        },
                        new
                        {
                            Id = 12,
                            CategoryName = "Categoria produto 12",
                            Description = "Descrição do produto 12",
                            Name = "Produto 12",
                            Price = 120m,
                            image_url = "http://teste.com"
                        },
                        new
                        {
                            Id = 13,
                            CategoryName = "Categoria produto 13",
                            Description = "Descrição do produto 13",
                            Name = "Produto 13",
                            Price = 130m,
                            image_url = "http://teste.com"
                        },
                        new
                        {
                            Id = 14,
                            CategoryName = "Categoria produto 14",
                            Description = "Descrição do produto 14",
                            Name = "Produto 14",
                            Price = 140m,
                            image_url = "http://teste.com"
                        },
                        new
                        {
                            Id = 15,
                            CategoryName = "Categoria produto 15",
                            Description = "Descrição do produto 15",
                            Name = "Produto 15",
                            Price = 150m,
                            image_url = "http://teste.com"
                        },
                        new
                        {
                            Id = 16,
                            CategoryName = "Categoria produto 16",
                            Description = "Descrição do produto 16",
                            Name = "Produto 16",
                            Price = 160m,
                            image_url = "http://teste.com"
                        },
                        new
                        {
                            Id = 17,
                            CategoryName = "Categoria produto 17",
                            Description = "Descrição do produto 17",
                            Name = "Produto 17",
                            Price = 170m,
                            image_url = "http://teste.com"
                        },
                        new
                        {
                            Id = 18,
                            CategoryName = "Categoria produto 18",
                            Description = "Descrição do produto 18",
                            Name = "Produto 18",
                            Price = 180m,
                            image_url = "http://teste.com"
                        },
                        new
                        {
                            Id = 19,
                            CategoryName = "Categoria produto 19",
                            Description = "Descrição do produto 19",
                            Name = "Produto 19",
                            Price = 190m,
                            image_url = "http://teste.com"
                        },
                        new
                        {
                            Id = 20,
                            CategoryName = "Categoria produto 20",
                            Description = "Descrição do produto 20",
                            Name = "Produto 20",
                            Price = 200m,
                            image_url = "http://teste.com"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
